version: "3"

services:
  php:
    build: ./php
    volumes:
      - ./php/html:/var/www/html
    ports:
      - 8000:80
    container_name: php_container

  mysql:
    build: ./mysql
    volumes:
      - ./sql:/user_sql
      - ./mysql/save_data:/var/lib/mysql #データの永続化
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    container_name: mysql_container

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"
